### ISSUE TITLE
Android device import issue 

### ISSUE THREAD

**Issue by jadavbheda** [jcsaaddupuy/python-xbmc#10]
__Why xbmcjson import fails in android system.__
OS = Android 4.4.2  (kernel: Linux 3.0.36+)
```
05:17:09 T:1866865248   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: ('invalid syntax', ('<string>', 4, 2, '  '))
                                            Traceback (most recent call last):
                                              File "/mnt/internal_sd/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.test/default.py", line 5, in <module>
                                                from xbmcjson import XBMC
                                              File "/mnt/internal_sd/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.test/xbmcjson.py", line 106, in <module>
                                                exec (s)
                                            SyntaxError: ('invalid syntax', ('<string>', 4, 2, '  '))
                                            -->End of Python script error report<--
```

**Comment by jcsaaddupuy** [comment]
Hi.
Seems like the dynamic [exec statement](https://github.com/jcsaaddupuy/python-xbmc/blob/master/xbmcjson/xbmcjson.py#L100-L106) does not work.
Could you please change these [lines](https://github.com/jcsaaddupuy/python-xbmc/blob/master/xbmcjson/xbmcjson.py#L102-L104) to something simpler, like

```python
"""class %s(XBMCNamespace): pass"""
```

**Comment by jcsaaddupuy** [comment]
any new on this ?

**Comment by jcsaaddupuy** [comment]
Calls to `exec` have been removed in the latest release and should fix this.
Please reopen if it's not the case.
